In [1]:
"""
Exploratory Data Analysis

In statistics, exploratory data analysis (EDA) is an approach to analyzing data sets to summarize their main characteristics, 
often with visual methods
"""

'\nExploratory Data Analysis\n\nIn statistics, exploratory data analysis (EDA) is an approach to analyzing data sets to summarize their main characteristics, \noften with visual methods\n'

In [2]:
# Import the `libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Load in the data with `read_csv()`
digits = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tra",
                     header=None)

iris = pd.read_csv('Iris.csv')

In [4]:
# Print out `digits`
print(digits)

      0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  \
0      0   1   6  15  12   1   0   0   0   7 ...   0   0   0   6  14   7   1
1      0   0  10  16   6   0   0   0   0   7 ...   0   0   0  10  16  15   3
2      0   0   8  15  16  13   0   0   0   1 ...   0   0   0   9  14   0   0
3      0   0   0   3  11  16   0   0   0   0 ...   0   0   0   0   1  15   2
4      0   0   5  14   4   0   0   0   0   0 ...   0   0   0   4  12  14   7
5      0   0  11  16  10   1   0   0   0   4 ...   3   0   0  10  16  16  16
6      0   0   1  11  13  11   7   0   0   0 ...   0   0   0   1  13   5   0
7      0   0   8  10   8   7   2   0   0   1 ...   0   0   0   4  13   8   0
8      0   0  15   2  14  13   2   0   0   0 ...   0   0   0  10  12   5   0
9      0   0   3  13  13   2   0   0   0   6 ...   0   0   0   3  15  11   6
10     0   0   6  14  14  16  16   8   0   0 ...   0   0   0  10  12   0   0
11     0   0   0   3  16  11   1   0   0   0 ...   0   0   0   0   2  14  14
12     0   0   0   4  13  16  16   3   0   0 ...   0   0   0   0   5  15   4
13     0   0   7  12   6   2   0   0   0   0 ...   0   0   0   5  16   9   0
14     0   0   7  11  11   6   0   0   0   9 ...   0   0   0  14  16  12  10
15     0   1  10  15   8   0   0   0   0   6 ...   0   0   0   9  15   8   0
16     0   0   0   1  11   7   0   0   0   0 ...   0   0   0   0   3  15   0
17     0   0   5  12  16  16   3   0   0   0 ...   0   0   0   8  12   0   0
18     0   0   1   8  13  13   2   0   0   4 ...   0   0   0   1  13  12   4
19     0   0   0   2  13  12   4   0   0   0 ...   0   0   0   0   0  15   3
20     0   0   4  11  15  16  15   0   0   0 ...   0   0   0   6  14   2   0
21     0   0   4  10  13  11   1   0   0   2 ...   0   0   0   6  13  11   1
22     0   0   3  11  13  14   6   0   0   0 ...   0   0   0   3  13  10   0
23     0   0   1   4  11  13   7   0   0   2 ...   0   0   0   0   1  14   3
24     0   0   9  13   1   0   0   0   0   0 ...   5   0   0   4  15  16  16
25     0   0   9  16  11   0   0   0   0   4 ...   1   0   0  10  16   9   9
26     0   0   2  13   9   0   0   0   0   0 ...   0   0   0   3  16  14   4
27     0   0   0  10  12   0   0   0   0   0 ...   0   0   0   1  11  14  12
28     0   0   0   0  10  13   0   0   0   0 ...   0   0   0   0   0   8  15
29     0   0   7   9  13  11   2   0   0   6 ...   0   0   0  13  12   8   1
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..  ..
3793   0   0  15  15  16  14   1   0   0   3 ...   0   0   0  15  16  12   0
3794   0   0   2  13  16  15   4   0   0   0 ...   0   0   0   3  14   1   0
3795   0   0  12  16   7   0   0   0   0   2 ...   0   0   0  11  16  16  16
3796   0   0   0   3  13   0   0   0   0   0 ...   0   0   0   0   6  12   0
3797   0   0   0  12   8   0   0   0   0   0 ...   0   0   0   0  14   6   0
3798   0   0   0   9  12   0   0   0   0   0 ...   0   0   0   0  10  11   0
3799   0   0   5  16  13   1   0   0   0   0 ...   0   0   1   6  10  12  12
3800   0   0   6  16   8   0   0   0   0   2 ...   0   0   0   7  13  16  13
3801   0   0   5  16  11   0   0   0   0   1 ...   0   0   0   4  14  12   2
3802   0   1  12  16  14   4   0   0   0   8 ...   0   0   0  13  15  15  10
3803   0   0   3  14  13   3   0   0   0   0 ...   0   0   0   3  13  13   6
3804   0   0  12  16  16  10   1   0   0   0 ...   0   0   1  10  16  16  16
3805   0   0   0   8  11   0   0   0   0   0 ...   0   0   0   0   7  12   0
3806   0   1   9  16  14   6   0   0   0   5 ...   0   0   0  11  16   7   0
3807   0   0   4  14  15   3   0   0   0   0 ...   0   0   0   3  14  14   6
3808   0   2  15  16  15   1   0   0   0   3 ...   0   0   0  14  13  16  11
3809   0   0   5  15  16   6   0   0   0   0 ...   0   0   0   5  15  16  15
3810   0   0   4  16  11   1   0   0   0   0 ...   0   0   0   2  12  16  11
3811   0   0   0   0   7  11   1   0   0   0 ...   0   0   0   2   0   7  11
3812   0   0   0   6  13   0   0   0   0   0 ...   0   0   0   0   6   9   0
3813   0   0   0   6   8   0   0   0   0   0 ...   0   0   1   4   9   8   0
3814   0   0   9  16   6   0   0   0   0   2 ...   0   0   0  10  13   1   0
3815   0   0   9  16  12   1   0   0   0   3 ...   0   0   0   8  16  16  16
3816   0   1  10  16  16   4   0   0   0   8 ...   0   0   2  13  16  12   5
3817   0   0   6  16  11   0   0   0   0   1 ...   0   0   1   7  14  16  12
3818   0   0   5  13  11   2   0   0   0   2 ...   0   0   0   8  13  15  10
3819   0   0   0   1  12   1   0   0   0   0 ...   0   0   0   0   4   9   0
3820   0   0   3  15   0   0   0   0   0   0 ...   0   0   0   4  14  16   9
3821   0   0   6  16   2   0   0   0   0   0 ...   0   0   0   5  16  16  16
3822   0   0   2  15  16  13   1   0   0   0 ...   0   0   0   4  14   1   0

      62  63  64
0      0   0   0
1      0   0   0
2      0   0   7
3      0   0   4
4      0   0   6
5     16   6   2
6      0   0   5
7      0   0   5
8      0   0   0
9      0   0   8
10     0   0   7
11     1   0   1
12     0   0   9
13     0   0   5
14     1   0   3
15     0   0   0
16     0   0   4
17     0   0   7
18     0   0   8
19     0   0   4
20     0   0   7
21     0   0   8
22     0   0   5
23     0   0   9
24    16  16   1
25    13   6   2
26     0   0   0
27     1   0   6
28     2   0   1
29     0   0   8
...   ..  ..  ..
3793   0   0   5
3794   0   0   7
3795  16   8   2
3796   0   0   4
3797   0   0   4
3798   0   0   4
3799   2   0   9
3800   9   0   9
3801   0   0   0
3802   2   0   3
3803   0   0   0
3804   7   0   3
3805   0   0   4
3806   0   0   8
3807   0   0   0
3808   1   0   3
3809   1   0   0
3810   1   0   1
3811   0   0   1
3812   0   0   4
3813   0   0   4
3814   0   0   8
3815   8   0   9
3816   0   0   3
3817   1   0   9
3818   1   0   9
3819   0   0   4
3820   0   0   6
3821   5   0   6
3822   0   0   7

[3823 rows x 65 columns]

In [5]:
# This function gives information about mean, median, minimum and maximum values of quantity of data excluding NaN values

digits.describe()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
count,3823.0,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,...,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000,3823.000000
mean,0.0,0.301334,5.481821,11.805912,11.451478,5.505362,1.387392,0.142297,0.002093,1.960502,...,0.148313,0.000262,0.283024,5.855872,11.942977,11.461156,6.700497,2.105676,0.202197,4.497253
std,0.0,0.866986,4.631601,4.259811,4.537556,5.613060,3.371444,1.051598,0.088572,3.052353,...,0.767761,0.016173,0.928046,4.980012,4.334508,4.991934,5.775815,4.028266,1.150694,2.869831
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,0.000000,1.000000,10.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,10.000000,9.000000,0.000000,0.000000,0.000000,2.000000
50%,0.0,0.000000,5.000000,13.000000,13.000000,4.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,5.000000,13.000000,13.000000,6.000000,0.000000,0.000000,4.000000
75%,0.0,0.000000,9.000000,15.000000,15.000000,10.000000,0.000000,0.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,10.000000,15.000000,16.000000,12.000000,2.000000,0.000000,7.000000
max,0.0,8.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,5.000000,15.000000,...,12.000000,1.000000,10.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,9.000000

In [6]:
#head() - first 5 rows of dataframe, tail() - last 5 rows of dataframe

# Inspect the first 5 rows of `digits`
first = digits.head()

# Inspect the last 5 rows
last = digits.tail()

In [7]:
print(first)

   0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  62  \
0   0   1   6  15  12   1   0   0   0   7 ...   0   0   0   6  14   7   1   0
1   0   0  10  16   6   0   0   0   0   7 ...   0   0   0  10  16  15   3   0
2   0   0   8  15  16  13   0   0   0   1 ...   0   0   0   9  14   0   0   0
3   0   0   0   3  11  16   0   0   0   0 ...   0   0   0   0   1  15   2   0
4   0   0   5  14   4   0   0   0   0   0 ...   0   0   0   4  12  14   7   0

   63  64
0   0   0
1   0   0
2   0   7
3   0   4
4   0   6

[5 rows x 65 columns]

In [8]:
print(last)

      0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  \
3818   0   0   5  13  11   2   0   0   0   2 ...   0   0   0   8  13  15  10
3819   0   0   0   1  12   1   0   0   0   0 ...   0   0   0   0   4   9   0
3820   0   0   3  15   0   0   0   0   0   0 ...   0   0   0   4  14  16   9
3821   0   0   6  16   2   0   0   0   0   0 ...   0   0   0   5  16  16  16
3822   0   0   2  15  16  13   1   0   0   0 ...   0   0   0   4  14   1   0

      62  63  64
3818   1   0   9
3819   0   0   4
3820   0   0   6
3821   5   0   6
3822   0   0   7

[5 rows x 65 columns]

In [9]:
"""
Sampling the dataset

In case of a large dataset, it is recommended to take sample of it to get the feel of the data quickly. There are
two ways to do it. One involves making use of sample() function by inputing in the number of rows for which we need
the sample as parameter. Other method makes use of random package which has the modules sample(), range() and len()
and combination of these might be used to get the requisite sample of the dataset.
                
"""

'\nSampling the dataset\n\nIn case of a large dataset, it is recommended to take sample of it to get the feel of the data quickly. There are\ntwo ways to do it. One involves making use of sample() function by inputing in the number of rows for which we need\nthe sample as parameter. Other method makes use of random package which has the modules sample(), range() and len()\nand combination of these might be used to get the requisite sample of the dataset.\n                \n'

In [10]:
# Using sample() function

x = digits.sample(5)
print(x)

      0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  \
2315   0   5  16  15   5   0   0   0   0   3 ...   0   0   7  16  14  12  12
3150   0   0   8  14  14   9   0   0   0   1 ...   0   0   0  10  16  16  10
284    0   0   0   0   6  15   1   0   0   0 ...   0   0   0   0   0   4  12
2549   0   0   6  11   0   0   0   0   0   0 ...   0   0   0   4  13  16  10
584    0   1  10  16  16   9   0   0   0  11 ...   0   0   0  12  16  16  14

      62  63  64
2315   9   0   2
3150   1   0   8
284    0   0   1
2549   2   0   6
584    5   0   3

[5 rows x 65 columns]

In [11]:
# Using sample(), range() and len() functions included in random package

# import sample from random
from random import sample

# Create a random index
randomIndex = np.array(sample(range(len(digits)), 5))

# Get 5 random rows
digitsSample = digits.loc[randomIndex]

# Print the sample
print(digitsSample)

      0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  \
2987   0   0   0   0   5  14   3   0   0   0 ...   0   0   0   0   0   6  16
940    0   0   2  11  16  16  11   0   0   0 ...   0   0   0   3  12  15   6
1645   0   0   1  12  15   5   0   0   0   0 ...   0   0   0   0  12  16  10
512    0   0   8  16   9   0   0   0   0   2 ...   0   0   0  10  16  13   5
350    0   0   0  13  14   2   0   0   0   0 ...   1   0   0   1  11  16  16

      62  63  64
2987   1   0   1
940    0   0   8
1645   0   0   6
512    0   0   9
350   10   0   6

[5 rows x 65 columns]

In [12]:
# Further inspection of data with query() function

# Petal length greater than sepal length?
iris.query('PetalLengthCm > SepalLengthCm')

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [13]:
# Petal length equals sepal length?
iris.query('PetalLengthCm == SepalLengthCm')

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [14]:
# Petal length less than sepal length?
iris.query('PetalLengthCm < SepalLengthCm')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
...,...,...,...,...,...,...
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
#iris.head()

In [16]:
# Get columns
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [17]:
# Checks whether null values are there in the dataset

pd.isnull('Iris')

False